### ISSUE TITLE
read gzipped files

### ISSUE THREAD

**Issue by sjanssen2** [jlab/algorithm_vxdetector#14]
is your program able to read form `*.fastq.gz` instead of `*.fastq`? That would speed up things a lot.

https://github.com/jlab/algorithm_vxdetector/blob/e22decf634af24c4f85ae8eaf0a5bbd0494aa637/vxdetector/interact_bowtie2.py#L25

**Comment by JGroos-16** [comment]
Yes, the program can handle both .fastq and .fastq.gz files.
